name: BSBase Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build_windows:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/Binaries/

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: Generate project files
        run: sh ${{ github.workspace }}/Scripts/Setup.sh
      # Build the whole project with Ninja (which is spawn by CMake).
      - name: Build
        run: sh ${{ github.workspace }}/Scripts/Build.sh